FROM node:18.18.2-slim AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .
COPY prisma ./prisma/
RUN npm run build
RUN npx prisma generate

FROM node:18.18.2-slim

WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install -y openssl && \
    rm -rf /var/lib/apt/lists/*

COPY package*.json ./
COPY prisma ./prisma/
COPY --from=builder /usr/src/app/dist ./dist

RUN npm install --only=production && npx prisma generate

EXPOSE 3001

CMD ["node", "dist/main.js"]