version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: roomrise
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./packages/backend
      dockerfile: ../../Dockerfile.backend
    env_file:
      - ./packages/backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - db

